### ISSUE TITLE
On Ubuntu 16.04, CINDER_BOOST_USE_SYSTEM fails to produce working binaries

### ISSUE THREAD

**Issue by dankegel** [cinder/Cinder#1544]
To reproduce, get a fresh Ubuntu 16.04 machine, then do
```
sudo apt-get update
sudo apt-get install \
        cmake \
        gstreamer1.0-alsa \
        gstreamer1.0-libav \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-pulseaudio \
        libasound2-dev \
        libboost-all-dev \
        libcurl4-gnutls-dev \
        libfontconfig1-dev \
        libgstreamer1.0-dev \
        libgstreamer-plugins-bad1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        libmpg123-dev \
        libpulse-dev \
        libsndfile1 \
        libsndfile1-dev \
        libxcursor-dev \
        libxi-dev \
        libxinerama-dev \
        libxrandr-dev \
        zlib1g-dev

git clone --recursive https://github.com/cinder/Cinder.git

cd Cinder
git checkout android_linux
rm -rf build
mkdir build
cd build
cmake -DCINDER_BOOST_USE_SYSTEM:BOOL=true ..
make -j4
cd ../samples/BasicApp/proj/cmake
rm -rf build
mkdir build
cd build
cmake ..
make -j4
```

The resulting samples/BasicApp/proj/cmake/build/Debug/BasicApp should run, but
instead it crashes with SIGSEGV inside boost::filesystem::path::parent_path()

The problem is that, when really using system boost, it is inappropriate to give the 
compile option D_GLIBCXX_USE_CXX11_ABI=0.

**Comment by richardeakin** [comment]
Should be fixed by #1546, please let us know if it works for you. cheers, Rich

**Comment by dankegel** [comment]
Thanks, but I'm afraid that's not quite enough.  I was going to submit a pull request
with a more complete fix, but I wanted to make sure it didn't break 'make test'...
so I had to pause to implement 'make test' first, see
https://github.com/cinder/Cinder/issues/1548

**Comment by PetrosKataras** [comment]
@dankegel may i ask what the issue exactly is here? Thanks, Petros

**Comment by dankegel** [comment]
CINDER_BOOST_USE_SYSTEM still fails to use system boost headers.  Also, seems to be some other problem causing test failure.  

(I hope the cake test change lands soon, easier to not juggle two changes.)
