### ISSUE TITLE
OS X 10.10 emits warning when switching to fullscreen at startup 

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#584]
When adding `settings->setFullScreen( true );` to prepareSettings() in OS X 10.10, the following warning / stacktrace is printed (tested on master branch):

```
2014-11-14 19:32:52.227 windowTest[85547:5829855] NSWindow warning: adding an unknown subview: <NSView: 0x10645c0>
2014-11-14 19:32:52.244 windowTest[85547:5829855] Call stack:
(
	0   AppKit                              0x917fa776 -[NSThemeFrame addSubview:] + 108
	1   AppKit                              0x910a1d77 -[NSView replaceSubview:with:] + 152
	2   AppKit                              0x9192b4d7 __60-[NSView(NSFullScreenMode) enterFullScreenMode:withOptions:]_block_invoke + 178
	3   AppKit                              0x91191bd7 NSPerformWithScreenUpdatesDisabled + 97
	4   AppKit                              0x9192b3cd -[NSView(NSFullScreenMode) enterFullScreenMode:withOptions:] + 3147
	5   windowTest                          0x0007d00c -[CinderView setFullScreen:options:] + 1036
	6   windowTest                          0x000430e7 -[WindowImplBasicCocoa setFullScreen:options:] + 135
	7   windowTest                          0x00040d1b -[AppImplCocoaBasic applicationDidFinishLaunching:] + 1403
```

Though the message is massively ugly, it does appear to still work. @andrewfb tried using the NSFullScreenModeSetting setting, which he found in Apple's [OpenCL N-Body](https://developer.apple.com/library/mac/samplecode/OpenCL_NBody_Simulation_Example/Listings/Sources_View_OpenGLView_mm.html) sample, but this seems to stop full screen from working altogether.

**Comment by pizthewiz** [comment]
Want a PR for this? I think a workaround is needed while the AppKit team looks into it.

**Comment by richardeakin** [comment]
I was hoping to hear back at least what they thought the diagnosis is, but if that doesn't happen soon then I'd say go for it.

**Comment by pizthewiz** [comment]
Unfortunately it doesn't seem as though Radar issues provide much external visibility without using a DTS incident. We might have more luck getting confirmation of the issue in the developer forum thread.

**Comment by pizthewiz** [comment]
Any further thoughts on this? I doubt there would be any harm in leaving the window's content view in place and instead adding the `CinderView` as a subview of that:
```objective-c
[winImpl->mWin.contentView addSubview:winImpl->mCinderView];
```

**Comment by richardeakin** [comment]
I think we should make the change, avoid the log spew.  Do you want to send a PR for the change? Probably best to do it against glNext since 0.9.0 is right around the corner and most of app:: files moved during the app_refactor.

**Comment by richardeakin** [comment]
Fixed with #811

**Comment by richardeakin** [comment]
Reopenning as #811 was reverted due to resizing problems that it caused.

**Comment by pizthewiz** [comment]
Sorry I didn't catch this previously, strangely when fullscreen'ed the resizing behavior seemed fine, but I think the fullscreen support acts on the CinderView directly so it would skirt resizing issues. Setting the autoresize mask on the view seems to do the trick:
```Objective-C
// add CinderView as subview of window's content view to avoid NSWindow warning: https://github.com/cinder/Cinder/issues/584
[winImpl->mWin.contentView addSubview:winImpl->mCinderView];
winImpl->mCinderView.autoresizingMask = NSViewWidthSizable | NSViewHeightSizable;
```

**Comment by andrewfb** [comment]
Thanks for sticking with this @pizthewiz - looks like this did the trick (tested on both 10.9 and 10.10).

**Comment by interwebjill** [comment]
I am still getting the stacktrace message using Cinder 0.8.6 on 10.10. I am also getting noticeable stuttering in my app when using getFullScreen() that is not there in other display modes.

http://discourse.libcinder.org/t/setfullscreen-slows-down-app-produces-log

**Comment by balachandranc** [comment]
@interwebjill , that fix seems to be included in 0.9.0 release, not 0.8.6.

https://github.com/cinder/Cinder/commit/7dff4d837ac85eefa35944429aae1acf2987e724

**Comment by interwebjill** [comment]
errrr

**Comment by interwebjill** [comment]
Is there any hope of getting a fix for 0.8.6?

**Comment by pizthewiz** [comment]
You could build your own version of Cinder based off 0.8.6 and cherry pick 7dff4d8 into it?

**Comment by interwebjill** [comment]
Okay, I'll give that a try. So does this commit solve the performance slow-down issue in fullscreen mode?
